### ISSUE TITLE
how to add dts support for mt7620a chipset

### ISSUE THREAD

**Issue by qianguozheng** [mqmaker/linux#1]
@Mqmaker-Sugar , look at your kernel , it should be derived from MTK port to openwrt platform, but they have removed the dts, this make we config the i2c gpio serial drivers hard, can we add dts back into trunk ？ I don't know whether they have some reason must remove it, if you know please tell me, thanks,

**Comment by Mqmaker-Sugar** [comment]
We are sorry.  We just have mt7621 platform source code. I don't know the reason. If you want to support dts, I think that you should use upstreaming's openwrt.
